/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/webhooks/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save (update) an existing webhook */
        post: operations["saveWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new webhook */
        post: operations["createWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/save-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save additional profile details for the authenticated user */
        post: operations["saveDetails"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with username and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/login/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with a Google ID token */
        post: operations["loginWithGoogle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stripe/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Receive and process a Stripe webhook event */
        post: operations["stripeWebhookEntry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Search for maps based on search criteria */
        post: operations["searchMaps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/get": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get all maps */
        post: operations["getMaps"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Insert current build info (admin) */
        post: operations["insertCurrentBuildInfo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/{webhookId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get logs for a specific webhook */
        get: operations["getWebhookLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Refresh the current session tokens */
        get: operations["refresh"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a map by its ID */
        get: operations["getMapById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/buildinfo/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current build info */
        get: operations["getBuildInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all webhooks for the authenticated user */
        get: operations["getAllWebhooks"];
        /** List all webhooks for the authenticated user */
        put: operations["getAllWebhooks_2"];
        /** List all webhooks for the authenticated user */
        post: operations["getAllWebhooks_1"];
        /** List all webhooks for the authenticated user */
        delete: operations["getAllWebhooks_3"];
        /** List all webhooks for the authenticated user */
        options: operations["getAllWebhooks_6"];
        /** List all webhooks for the authenticated user */
        head: operations["getAllWebhooks_5"];
        /** List all webhooks for the authenticated user */
        patch: operations["getAllWebhooks_4"];
        trace?: never;
    };
    "/user/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Log out and clear auth cookies */
        get: operations["logout"];
        /** Log out and clear auth cookies */
        put: operations["logout_2"];
        /** Log out and clear auth cookies */
        post: operations["logout_1"];
        /** Log out and clear auth cookies */
        delete: operations["logout_3"];
        /** Log out and clear auth cookies */
        options: operations["logout_6"];
        /** Log out and clear auth cookies */
        head: operations["logout_5"];
        /** Log out and clear auth cookies */
        patch: operations["logout_4"];
        trace?: never;
    };
    "/lookups/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lookup reference data */
        get: operations["getAllLookups"];
        /** Get all lookup reference data */
        put: operations["getAllLookups_2"];
        /** Get all lookup reference data */
        post: operations["getAllLookups_1"];
        /** Get all lookup reference data */
        delete: operations["getAllLookups_3"];
        /** Get all lookup reference data */
        options: operations["getAllLookups_6"];
        /** Get all lookup reference data */
        head: operations["getAllLookups_5"];
        /** Get all lookup reference data */
        patch: operations["getAllLookups_4"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Webhook: {
            /** Format: int64 */
            id?: number;
            webhookLk?: string;
            /** Format: int64 */
            userId?: number;
            url?: string;
            secret?: string;
            activeFlg?: boolean;
            /** Format: date-time */
            createdAt?: string;
        };
        AuthToken: {
            /** Format: int64 */
            id?: number;
            accessToken?: string;
            refreshToken?: string;
        };
        AuthorizedUser: {
            /**
             * Format: int64
             * @description Unique user identifier
             */
            id?: number;
            /** @description User's login username or email */
            username?: string;
            /** @description Role lookup key (e.g. 'ADMIN', 'USER') */
            roleLk?: string;
            userDetails?: components["schemas"]["UserDetails"];
            authToken?: components["schemas"]["AuthToken"];
            /** Format: int32 */
            idAsInt?: number;
        };
        UserDetails: {
            displayName?: string;
            /** Format: int64 */
            userId?: number;
            /** Format: int64 */
            userDataId?: number;
        };
        User: {
            /**
             * Format: int64
             * @description Unique user identifier
             */
            id?: number;
            /** @description User's login username or email */
            username?: string;
            /** @description Role lookup key (e.g. 'ADMIN', 'USER') */
            roleLk?: string;
            userDetails?: components["schemas"]["UserDetails"];
            /** Format: int32 */
            idAsInt?: number;
        };
        UserAuthenticationForm: {
            /**
             * Format: int64
             * @description Unique user identifier
             */
            id?: number;
            /** @description User's login username or email */
            username?: string;
            /** @description Role lookup key (e.g. 'ADMIN', 'USER') */
            roleLk?: string;
            userDetails?: components["schemas"]["UserDetails"];
            /** @description Authentication method (e.g. 'password', 'GOOGLE_OAUTH2') */
            authenticationMethodLk?: string;
            /** @description Provider-issued token used for OAuth2 or SSO authentication flows */
            specialToken?: string;
            parameters?: {
                [key: string]: Record<string, never>;
            };
            /** Format: int32 */
            idAsInt?: number;
        };
        MessageObject: {
            /** Format: date-time */
            timestamp?: string;
            type?: string;
            message?: string;
            data?: Record<string, never>;
            payload?: Record<string, never>;
        };
        MessageVoid: {
            /** Format: date-time */
            timestamp?: string;
            type?: string;
            message?: string;
            data?: Record<string, never>;
            payload?: Record<string, never>;
            messages?: components["schemas"]["MessageObject"][];
        };
        MapSearchForm: {
            /** @description Search term for maps */
            searchTerm?: string;
            /** @description Categories to search by */
            categories?: string[];
            /** @description Only show maps that are reviewed */
            onlyShowReviewed?: boolean;
            /** @description Only show maps that are not reviewed */
            onlyShowNotReviewed?: boolean;
        };
        /** @description Map model relative to a game */
        Map: {
            /**
             * Format: date-time
             * @description The date and time when the record was created
             * @example 2023-01-01T12:00:00
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description The date and time when the record was last updated
             * @example 2023-01-01T12:00:00
             */
            updatedAt?: string;
            /**
             * Format: int64
             * @description Map ID
             */
            mapId?: number;
            /** @description Map name */
            name?: string;
            /** @description Game link associated with the map */
            gameLk?: string;
            /** @description A list of categories lookups associated with the map */
            categories?: string[];
            /** @description Map images associated with the map */
            mapImage?: components["schemas"]["MapImage"][];
            /** @description Map reviews associated with the map */
            mapReview?: components["schemas"]["MapReview"][];
        };
        MapImage: {
            /**
             * Format: int64
             * @description Map image ID
             */
            mapImageId?: number;
            /**
             * Format: int64
             * @description Map ID associated with the image
             */
            mapId?: number;
            /** @description Image URL */
            imagePath?: string;
            /** @description System flag indicating whether the image is a system image or not */
            systemFlg?: boolean;
            /**
             * Format: int32
             * @description Sequence number of the map image, the lowest sequence number is the first image to be displayed
             */
            seqNo?: number;
        };
        MapReview: {
            /**
             * Format: date-time
             * @description The date and time when the record was created
             * @example 2023-01-01T12:00:00
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description The date and time when the record was last updated
             * @example 2023-01-01T12:00:00
             */
            updatedAt?: string;
            /**
             * Format: int64
             * @description Map review ID
             */
            mapReviewId?: number;
            /** Format: int64 */
            userId?: number;
            review?: string;
            /** Format: int32 */
            rating?: number;
            images?: components["schemas"]["MapImage"][];
        };
        WebhookLog: {
            /** Format: int64 */
            id?: number;
            /** Format: int64 */
            webhookId?: number;
            eventData?: Record<string, never>;
            /** Format: int32 */
            responseStatus?: number;
            responseBody?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        BuildInfo: {
            buildName?: string;
            buildVersion?: string;
            commitHash?: string;
            /** Format: date */
            buildDate?: string;
        };
        ResponseObjectVoid: {
            /** Format: date-time */
            timestamp?: string;
            type?: string;
            message?: string;
            data?: Record<string, never>;
        };
        Lookups: {
            lookups?: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            cacheTimestamp?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type Webhook = components['schemas']['Webhook'];
export type AuthToken = components['schemas']['AuthToken'];
export type AuthorizedUser = components['schemas']['AuthorizedUser'];
export type UserDetails = components['schemas']['UserDetails'];
export type User = components['schemas']['User'];
export type UserAuthenticationForm = components['schemas']['UserAuthenticationForm'];
export type MessageObject = components['schemas']['MessageObject'];
export type MessageVoid = components['schemas']['MessageVoid'];
export type MapSearchForm = components['schemas']['MapSearchForm'];
export type Map = components['schemas']['Map'];
export type MapImage = components['schemas']['MapImage'];
export type MapReview = components['schemas']['MapReview'];
export type WebhookLog = components['schemas']['WebhookLog'];
export type BuildInfo = components['schemas']['BuildInfo'];
export type ResponseObjectVoid = components['schemas']['ResponseObjectVoid'];
export type Lookups = components['schemas']['Lookups'];
export type $defs = Record<string, never>;
export interface operations {
    saveWebhook: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Webhook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"];
                };
            };
        };
    };
    createWebhook: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Webhook"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"];
                };
            };
        };
    };
    saveDetails: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserDetails"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAuthenticationForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorizedUser"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserAuthenticationForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorizedUser"];
                };
            };
        };
    };
    loginWithGoogle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorizedUser"];
                };
            };
        };
    };
    stripeWebhookEntry: {
        parameters: {
            query?: never;
            header: {
                "Stripe-Signature": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["MessageVoid"];
                };
            };
        };
    };
    searchMaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MapSearchForm"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Map"][];
                };
            };
        };
    };
    getMaps: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Map"][];
                };
            };
        };
    };
    insertCurrentBuildInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": boolean;
                };
            };
        };
    };
    getWebhookLogs: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path: {
                webhookId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WebhookLog"][];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthorizedUser"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query: {
                user: components["schemas"]["User"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["User"];
                };
            };
        };
    };
    getMapById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Map"];
                };
            };
        };
    };
    getBuildInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BuildInfo"];
                };
            };
        };
    };
    getAllWebhooks: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_6: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    getAllWebhooks_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Webhook"][];
                };
            };
        };
    };
    logout: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_2: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_1: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_3: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_6: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_5: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    logout_4: {
        parameters: {
            query: {
                user: components["schemas"]["AuthorizedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ResponseObjectVoid"];
                };
            };
        };
    };
    getAllLookups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_3: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_6: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_5: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
    getAllLookups_4: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["Lookups"];
                };
            };
        };
    };
}
